name: untitled
description: A Flutter app to learn and practice multiplication tables.

# Add this block 👇
environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  go_router: ^13.1.0
  font_awesome_flutter: ^10.7.0
  flutter_screenutil: ^5.9.0
